#! /bin/bash

commands=("proj" "templ")
plugins=("archive.sh")

usage() {
    echo "Usage: poli COMMANDS ARGS [OPTIONS]                       "
    echo "                                                          "
    echo "COMMANDS                                                  "
    echo "                                                          "

    for command in "${commands[@]}"; do
        ".poliglota/scripts/${command}.sh" --description
    done

    for plugin in "${plugins[@]}"; do
        ".poliglota/scripts/${plugin}" --description
    done

}

## Parsing arguments
case $1 in

    ## Commands
    "proj")
        shift
        .poliglota/scripts/proj.sh "$@"
        exit
    ;;
    "templ")
        shift
        .poliglota/scripts/templ.sh "$@"
        exit
    ;;

    ## Plugins
    "archive")
        shift
        .plugins/archive.sh "$@"
        exit
    ;;
    ## Errors
    *)
        usage

esac